### PR TITLE
Fixes NullReferenceException with recursive GetVortoValue

### PR DESCRIPTION
**Pull request by drangus**
Fix for NullReferenceException when calling GetVortoValue : allow return of defaultValue or if the recursive parameter set true traversal up the tree.

### CODE REVIEW

**Comment by leekelleher** [comment]
Thanks @drangus! 🎉  I've updated the PR with whitespace formatting - to match the current code style.

Once @mattbrailsford is happy, we can merge it in 👍

**Comment by sniffdk** [comment]
Was just about to submit a PR for this as well. This change should also be added to DoInnerHasVortoValue.

**Review by sniffdk — CHANGES_REQUESTED** [review]
Imho the unnecessary nesting should be replaced with something like
if (prop == null)
{
    return defaultValue;
}

**Comment by tristanjthompson** [comment]
Was just going to raise an issue/PR for this!  Might it be approved/merged/released soon?  Anything I can do to help?

**Comment by mattbrailsford** [comment]
This has now been merged in (and tweaked as per @sniffdk's suggestions) and is available via the build server https://ci.appveyor.com/project/UMCO/umbraco-vorto/build/1.6.1.114/artifacts or via MyGet https://www.myget.org/gallery/umbraco-packages.

I'll have a chat with @leekelleher to see if we push a release out now, or try and address any of the open issues first.

**Comment by drangus** [comment]
The applied patch doesn't allow recursion! 

Change to:
```
if (prop == null)
{
    // PR #100 - Prevent generation of NullReferenceException: allow return of defaultValue or traversal up the tree if prop is null
    //return defaultValue;
    return recursive && content.Parent != null? content.Parent.DoGetVortoValue<T>(propertyAlias, cultureName, recursive, defaultValue) : defaultValue;
}
```

**Pull request merged**
