### PR TITLE
Upgraded to C# 6 language features

### PR DESCRIPTION
**Pull request by anth12**

### CODE REVIEW

**Comment by mattbrailsford** [comment]
I've never been quite sure whether to use these features yet. What demands does it put on the project? Does it require a minimum version of VS or .NET to compile? I'm guessing this might be why the build has failed.

**Comment by anth12** [comment]
C# 6 was released in 2014 so I would consider it good for use. The string interpolation & propagation features make no difference once compiled, they just make the source code more concise and cleaner.

Yes it looks as though the build is targeting C# 5 as the `$` character is showing as unrecognised.

**Comment by anth12** [comment]
> Does it require a minimum version of VS or .NET to compile?

The targeted version of .net is not affected. The syntax is compatible with 2013, using a [NuGet package](https://www.nuget.org/packages/Microsoft.Net.Compilers/), but VS2015 has support out of the box.

There is no specific benefit to merging but if you decide to the AppVeyor build config will need to be updated, which can either be done through the web UI or the appveyor.yml file...

**Comment by leekelleher** [comment]
I read a blog post about [building C#6 code with AppVeyor](http://kristian.hellang.com/building-csharp-6-code-with-appveyor/), turns out that it's the VS solution file that needs updating;

from...

    VisualStudioVersion = 12.0.31101.0

to...

    VisualStudioVersion = 14.0.22823.1

(or later version - ultimately so it's at least VS2015 RTM or above)

---

@mattbrailsford I think we should do this across all the UMCO packages, in due course.

**Comment by Jeavon** [comment]
Need to add:

`os: Visual Studio 2015`

as the first line in appveyor.yml

**Comment by Jeavon** [comment]
Also I would recommend that you change the `ToolsVersion` to 14 from 12 in each csproj although it may not be strictly necessary it will help when people open the solution to choose vs2015 instead of vs2013 if they have both installed

**Comment by Jeavon** [comment]
I think ToolsVersion should be updated to 14 or totally removed from https://github.com/umco/umbraco-vorto/blob/master/build/package.proj#L2

**Comment by Jeavon** [comment]
Darn BCL issue, I'll clone your fork, expect a PR for your PR :)

**Comment by Jeavon** [comment]
@anth12 need to update build-appveyor.cmd and it should build

`CALL "%programfiles(x86)%\MSBuild\14.0\Bin\amd64\MsBuild.exe" build\package.proj`

**Comment by anth12** [comment]
Thanks for the help @Jeavon, not used AppVeyor before.

**Comment by leekelleher** [comment]
@anth12 We lovingly know @Jeavon as our "AppVeyor Rockstar" :metal:

**Comment by Jeavon** [comment]
@leekelleher 👌:sparkles:

**Pull request merged**
