### PR TITLE
Ad public API XML docs

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
Adds XML documentation for the public API to aid intellisense.

https://twitter.com/James_M_South/status/874283909009125376

### CODE REVIEW

**Comment by abjerner** [comment]
Just to be annoying:

The `<see cref="T"/>` at line 160 will trigger a warning, since it doesn't know how to resolve `T` to a type. It should be `<typeparamref name="T"/>` instead.

https://github.com/umco/umbraco-vorto/pull/90/files#diff-e3939f24b4a5c08135ae25b1a6faf5d5R160

Otherwise good job on the XML documentation 👍  it's always a joy to have that for intellisense and similar.

**Comment by JimBobSquarePants** [comment]
@abjerner Good spot! That's it fixed now 👍

**Comment by JimBobSquarePants** [comment]
Double Yay!

**Comment by mattbrailsford** [comment]
Cheers bud. Sorry it took so long.

**Pull request merged**
